library("data.table")
library("questionr")
library("questionr")

formantData <- as.data.table(read.table("/Users/hannahrowe/Google\ Drive/My\ Drive/Research/Scripts/4\ R\ Scripts/Formant_Data_For_R.csv", header=TRUE,sep=","))

formantData <- rename.variable(formantData, "OnsetFreq_1", "F1OnsetFreq")
formantData <- rename.variable(formantData, "OnsetFreq_2", "F2OnsetFreq")
formantData <- rename.variable(formantData, "OffsetFreq_1", "F1OffsetFreq")
formantData <- rename.variable(formantData, "OffsetFreq_2", "F2OffsetFreq")
formantData <- rename.variable(formantData, "Range_1", "F1Range")
formantData <- rename.variable(formantData, "Range_2", "F2Range")
formantData <- rename.variable(formantData, "Slope_1", "F1Slope")
formantData <- rename.variable(formantData, "Slope_2", "F2Slope")
formantData <- rename.variable(formantData, "Ratio_1", "F1Ratio")
formantData <- rename.variable(formantData, "Ratio_2", "F2Ratio")

syllable <- formantData[,
                        list(VOT,
                             Vow,
                             Syll = sum(VOT, Vow),
                             F1OnsetFreq,
                             F2OnsetFreq,
                             ConSpace = F2OnsetFreq-F1OnsetFreq,
                             F1OffsetFreq,
                             F2OffsetFreq,
                             VowSpace = F2OffsetFreq-F1OffsetFreq,
                             F1Range = abs(F1Range),
                             F2Range = abs(F2Range),
                             F1Slope,
                             F2Slope,
                             F1xF2Xcorr,
                             F1xF2Corr,
                             F1xF2Cov,
                             F1Ratio,
                             F2Ratio,
                             F1Vel,
                             F1Accel,
                             F1Jerk,
                             F2Vel,
                             F2Accel,
                             F2Jerk),
                        by = list(Participant, Rep, Task)]
proportions <- syllable[,
                        list(VOT,
                             Vow,
                             Syll,
                             VOTVowProp = VOT/Vow,
                             VOTSyllProp = VOT/Syll,
                             VowSyllProp = Vow/Syll,
                             F1OnsetFreq,
                             F2OnsetFreq,
                             ConSpace,
                             F1OffsetFreq,
                             F2OffsetFreq,
                             VowSpace,
                             F1Range,
                             F2Range,
                             F1Slope,
                             F2Slope,
                             F1xF2Xcorr,
                             F1xF2Corr,
                             F1xF2Cov,
                             F1Ratio,
                             F2Ratio,
                             F1Vel,
                             F1Accel,
                             F1Jerk,
                             F2Vel,
                             F2Accel,
                             F2Jerk),
                        by = list(Participant, Rep, Task)]
precision <- proportions[,
                         list(Task,
                              VOT,
                              Vow,
                              Syll,
                              VOTVowProp,
                              VOTSyllProp,
                              VowSyllProp,
                              F1OnsetFreq,
                              F2OnsetFreq,
                              ConSpace,
                              F1OffsetFreq,
                              F2OffsetFreq,
                              VowSpace,
                              F1Range,
                              F2Range,
                              F1Slope,
                              F2Slope,
                              F1xF2Xcorr,
                              F1xF2Corr,
                              F1xF2Cov,
                              F1Ratio,
                              F2Ratio,
                              F1Vel,
                              F1Accel,
                              F1Jerk,
                              F2Vel,
                              F2Accel,
                              F2Jerk,
                              PhonVar_VOT = sd(VOT),
                              PhonVar_Vow = sd(Vow),
                              PhonVar_Syll = sd(Syll),
                              PhonVar_VOTVowProp = sd(VOTVowProp),
                              PhonVar_VOTSyllProp = sd(VOTSyllProp),
                              PhonVar_VowSyllProp = sd(VowSyllProp),
                              PhonVar_F1OnsetFreq = sd(F1OnsetFreq),
                              PhonVar_F2OnsetFreq = sd(F2OnsetFreq),
                              PhonVar_ConSpace = sd(ConSpace),
                              PhonVar_F1OffsetFreq = sd(F1OffsetFreq),
                              PhonVar_F2OffsetFreq = sd(F2OffsetFreq),
                              PhonVar_VowSpace = sd(VowSpace),
                              PhonVar_F1Range = sd(F1Range),
                              PhonVar_F2Range = sd(F2Range),
                              PhonVar_F1Slope = sd(F1Slope),
                              PhonVar_F2Slope = sd(F2Slope),
                              PhonVar_F1xF2Xcorr = sd(F1xF2Xcorr),
                              PhonVar_F1xF2Corr = sd(F1xF2Corr),
                              PhonVar_F1xF2Cov = sd(F1xF2Cov),
                              PhonVar_F1Ratio = sd(F1Ratio),
                              PhonVar_F2Ratio = sd(F2Ratio),
                              PhonVar_F1Vel = sd(F1Vel),
                              PhonVar_F1Accel = sd(F1Accel),
                              PhonVar_F1Jerk = sd(F1Jerk),
                              PhonVar_F2Vel = sd(F2Vel),
                              PhonVar_F2Accel = sd(F2Accel),
                              PhonVar_F2Jerk = sd(F2Jerk)),
                         by = list(Participant, Rep)]
precision_consistency <- precision[,
                                   list(Rep,
                                        VOT,
                                        Vow,
                                        Syll,
                                        VOTVowProp,
                                        VOTSyllProp,
                                        VowSyllProp,
                                        F1OnsetFreq,
                                        F2OnsetFreq,
                                        ConSpace,
                                        F1OffsetFreq,
                                        F2OffsetFreq,
                                        VowSpace,
                                        F1Range,
                                        F2Range,
                                        F1Slope,
                                        F2Slope,
                                        F1xF2Xcorr,
                                        F1xF2Corr,
                                        F1xF2Cov,
                                        F1Ratio,
                                        F2Ratio,
                                        F1Vel,
                                        F1Accel,
                                        F1Jerk,
                                        F2Vel,
                                        F2Accel,
                                        F2Jerk,
                                        PhonVar_VOT,
                                        PhonVar_Vow,
                                        PhonVar_Syll,
                                        PhonVar_VOTVowProp,
                                        PhonVar_VOTSyllProp,
                                        PhonVar_VowSyllProp,
                                        PhonVar_F1OnsetFreq,
                                        PhonVar_F2OnsetFreq,
                                        PhonVar_ConSpace,
                                        PhonVar_F1OffsetFreq,
                                        PhonVar_F2OffsetFreq,
                                        PhonVar_VowSpace,
                                        PhonVar_F1Range,
                                        PhonVar_F2Range,
                                        PhonVar_F1Slope,
                                        PhonVar_F2Slope,
                                        PhonVar_F1xF2Xcorr,
                                        PhonVar_F1xF2Corr,
                                        PhonVar_F1xF2Cov,
                                        PhonVar_F1Ratio,
                                        PhonVar_F2Ratio,
                                        PhonVar_F1Vel,
                                        PhonVar_F1Accel,
                                        PhonVar_F1Jerk,
                                        PhonVar_F2Vel,
                                        PhonVar_F2Accel,
                                        PhonVar_F2Jerk,
                                        RepVar_VOT = (sd(VOT)/(mean(VOT)))*100,
                                        RepVar_Vow = (sd(Vow)/(mean(Vow)))*100,
                                        RepVar_Syll = (sd(Syll)/(mean(Syll)))*100,
                                        RepVar_VOTVowProp = (sd(VOTVowProp)/(mean(VOTVowProp)))*100,
                                        RepVar_VOTSyllProp = (sd(VOTSyllProp)/(mean(VOTSyllProp)))*100,
                                        RepVar_VowSyllProp = (sd(VowSyllProp)/(mean(VowSyllProp)))*100,
                                        RepVar_F1OnsetFreq = (sd(F1OnsetFreq)/(mean(F1OnsetFreq)))*100,
                                        RepVar_F2OnsetFreq = (sd(F2OnsetFreq)/(mean(F2OnsetFreq)))*100,
                                        RepVar_ConSpace = (sd(ConSpace)/(mean(ConSpace)))*100,
                                        RepVar_F1OffsetFreq = (sd(F1OffsetFreq)/(mean(F1OffsetFreq)))*100,
                                        RepVar_F2OffsetFreq = (sd(F2OffsetFreq)/(mean(F2OffsetFreq)))*100,
                                        RepVar_VowSpace = (sd(VowSpace)/(mean(VowSpace)))*100,
                                        RepVar_F1Range = (sd(F1Range)/(mean(F1Range)))*100,
                                        RepVar_F2Range = (sd(F2Range)/(mean(F2Range)))*100,
                                        RepVar_F1Slope = (sd(F1Slope)/(mean(F1Slope)))*100,
                                        RepVar_F2Slope = (sd(F2Slope)/(mean(F2Slope)))*100,
                                        RepVar_F1xF2Xcorr = (sd(F1xF2Xcorr)/(mean(F1xF2Xcorr)))*100,
                                        RepVar_F1xF2Corr = (sd(F1xF2Corr)/(mean(F1xF2Corr)))*100,
                                        RepVar_F1xF2Cov = (sd(F1xF2Cov)/(mean(F1xF2Cov)))*100,
                                        RepVar_F1Ratio = (sd(F1Ratio)/(mean(F1Ratio)))*100,
                                        RepVar_F2Ratio = (sd(F2Ratio)/(mean(F2Ratio)))*100,
                                        RepVar_F1Vel = (sd(F1Vel)/(mean(F1Vel)))*100,
                                        RepVar_F1Accel = (sd(F1Accel)/(mean(F1Accel)))*100,
                                        RepVar_F1Jerk = (sd(F1Jerk)/(mean(F1Jerk)))*100,
                                        RepVar_F2Vel = (sd(F2Vel)/(mean(F2Vel)))*100,
                                        RepVar_F2Accel = (sd(F2Accel)/(mean(F2Accel)))*100,
                                        RepVar_F2Jerk = (sd(F2Jerk)/(mean(F2Jerk)))*100),
                                   by = list(Participant, Task)]
data <- precision_consistency[,
                              list(Task,
                                   VOT,
                                   Vow,
                                   Syll,
                                   VOTVowProp,
                                   VOTSyllProp,
                                   VowSyllProp,
                                   F1OnsetFreq,
                                   F2OnsetFreq,
                                   ConSpace,
                                   F1OffsetFreq,
                                   F2OffsetFreq,
                                   VowSpace,
                                   F1Range,
                                   F2Range,
                                   F1Slope,
                                   F2Slope,
                                   F1xF2Xcorr,
                                   F1xF2Corr,
                                   F1xF2Cov,
                                   F1Ratio,
                                   F2Ratio,
                                   F1Vel,
                                   F1Accel,
                                   F1Jerk,
                                   F2Vel,
                                   F2Accel,
                                   F2Jerk,
                                   PhonVar_VOT,
                                   PhonVar_Vow,
                                   PhonVar_Syll,
                                   PhonVar_VOTVowProp,
                                   PhonVar_VOTSyllProp,
                                   PhonVar_VowSyllProp,
                                   PhonVar_F1OnsetFreq,
                                   PhonVar_F2OnsetFreq,
                                   PhonVar_ConSpace,
                                   PhonVar_F1OffsetFreq,
                                   PhonVar_F2OffsetFreq,
                                   PhonVar_VowSpace,
                                   PhonVar_F1Range,
                                   PhonVar_F2Range,
                                   PhonVar_F1Slope,
                                   PhonVar_F2Slope,
                                   PhonVar_F1xF2Xcorr,
                                   PhonVar_F1xF2Corr,
                                   PhonVar_F1xF2Cov,
                                   PhonVar_F1Ratio,
                                   PhonVar_F2Ratio,
                                   PhonVar_F1Vel,
                                   PhonVar_F1Accel,
                                   PhonVar_F1Jerk,
                                   PhonVar_F2Vel,
                                   PhonVar_F2Accel,
                                   PhonVar_F2Jerk,
                                   RepVar_VOT,
                                   RepVar_Vow,
                                   RepVar_Syll,
                                   RepVar_VOTVowProp,
                                   RepVar_VOTSyllProp,
                                   RepVar_VowSyllProp,
                                   RepVar_F1OnsetFreq,
                                   RepVar_F2OnsetFreq,
                                   RepVar_ConSpace,
                                   RepVar_F1OffsetFreq,
                                   RepVar_F2OffsetFreq,
                                   RepVar_VowSpace,
                                   RepVar_F1Range,
                                   RepVar_F2Range,
                                   RepVar_F1Slope,
                                   RepVar_F2Slope,
                                   RepVar_F1xF2Xcorr,
                                   RepVar_F1xF2Corr,
                                   RepVar_F1xF2Cov,
                                   RepVar_F1Ratio,
                                   RepVar_F2Ratio,
                                   RepVar_F1Vel,
                                   RepVar_F1Accel,
                                   RepVar_F1Jerk,
                                   RepVar_F2Vel,
                                   RepVar_F2Accel,
                                   RepVar_F2Jerk),
                              by = list(Participant, Rep)]

write.csv(data, file = "/Users/hannahrowe/Desktop/Formant_Data_For_Spreadsheets.csv")
